#!/bin/sh
set -e
if [ "$1" = remove ] || [ "$1" = upgrade ]; then
	if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
		systemctl disable openmiop.service >/dev/null 2>&1 || true
	fi
	dkms remove -m openmiop -v @VERSION@ --all >/dev/null 2>&1 || true
fi
exit 0
